### ISSUE TITLE
Name Brainstorming

### ISSUE THREAD

**Issue by omiinaya** [omiinaya/OKAJ#11]

**Comment by omiinaya** [comment]
Eyevent

**Comment by omiinaya** [comment]
Venton

**Comment by omiinaya** [comment]
Beeherd

**Comment by Keylasan** [comment]
burnerTag

**Comment by Keylasan** [comment]
HearMe

**Comment by Keylasan** [comment]
JustBee
justB

**Comment by Keylasan** [comment]
doVent is good to take - only online reference is a close norwegian word and it must be a sign, that's my fav language ever. 

also Freelease is good to take. only thing online is 'freelease copiers'

**Comment by Arobl034** [comment]
venTTown

**Comment by omiinaya** [comment]
Nimity

**Comment by omiinaya** [comment]
VentBook

**Comment by omiinaya** [comment]
Respire

**Comment by Keylasan** [comment]
hi guys, beeherd has the most amount of votes. I will proceed with the design of the site with this concept of bees in mind. Overall colors, black/white, purple and minimal yellow and light blue.

everyone align?
