### ISSUE TITLE
Add animated hero elements

### ISSUE THREAD

**Issue by omiinaya** [omiinaya/OKAJ#61]
Keyla’s idea about the “it’s okay to feel” *rotating words*

**Comment by Keylasan** [comment]
Two of my word changing components aren't working. It'sOKto and Words in ./components -----animation in css is not showing up in react as my Mood Disorders animation. Task ----resolve today. To do: Finish 2 pages css and make Support button work in both. Find text editor for post page and a small one for homepage. I can do this.
