### ISSUE TITLE
Find or create a text editor for the posting page.

### ISSUE THREAD

**Issue by omiinaya** [omiinaya/OKAJ#63]
something similar to reddit.com/submit would be nice

**Comment by Arobl034** [comment]
npm install --save @ckeditor/ckeditor5-react @ckeditor/ckeditor5-build-classic

npm i html-react-parser

**Comment by omiinaya** [comment]
next time do npm add both of those so when other people git pull all they have to do is npm install

**Comment by omiinaya** [comment]
good job. looks great!
